// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {menu} from '../models';

export function Greet(arg1:string):Promise<main.Msg>;

export function Quit(arg1:menu.CallbackData):Promise<void>;
